#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 16:07:14 2020

@author: roryh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("./output/100.csv") ### CHANGE HERE
X = np.array(df["x"])
Y = np.array(df["y"])


pic = np.zeros((max(Y)+1, max(X)+1)) # pic holds the values for S,I,R or X
base = np.zeros((max(Y)+1, max(X)+1)) # base holds the full image of ireland and is drawn behind pic

for i in df.values: # iterate through rows of df
    pic[int(i[1])][int(i[0])] = i[3] ## i[3] references I here, play with this to output S,I,R or X
    base[int(i[1])][int(i[0])] = 1 ## base = 1 for areas where the population > 0
    
pic = pic[::-1]
pic = np.ma.masked_where(pic < 1, pic) # don't plot areas where I < 1
base = base[::-1]
base = np.ma.masked_where(base == 0, base) # don't plot areas with no population

fig = plt.figure(figsize = (10,10))
ax = fig.add_subplot(1, 1, 1)

ax.set_facecolor('tab:gray') # background colour
ax.imshow(base, cmap = plt.get_cmap('inferno'),alpha = 0.5,interpolation="nearest",origin='lower')
im = ax.imshow(pic, alpha = 1,  cmap = plt.get_cmap('inferno'), aspect="equal",interpolation="nearest", vmin = 1, vmax = 1000)
fig.colorbar(im, ax=ax)

plt.savefig("example.png")
